-- OceanCore Sub-category setup
create table if not exists public.subcategories (id bigint generated by default as identity primary key, category_id bigint not null references public.categories(id) on delete cascade, name text not null, description text, created_at timestamptz not null default now(), unique(category_id,name));
alter table public.products add column if not exists subcategory_id bigint references public.subcategories(id) on delete set null;
alter table public.subcategories enable row level security;
drop policy if exists "Public can view subcategories" on public.subcategories;
create policy "Public can view subcategories" on public.subcategories for select to anon, authenticated using (true);
drop policy if exists "Admins manage subcategories" on public.subcategories;
create policy "Admins manage subcategories" on public.subcategories for all to authenticated using (exists (select 1 from public.admin_users where public.admin_users.user_id=auth.uid())) with check (exists (select 1 from public.admin_users where public.admin_users.user_id=auth.uid()));
